- name: Install nginx only on Ubuntu
  hosts: local
  become: yes

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      when: ansible_distribution == "Ubuntu"
    - name: Install nginx
      yum:
        name: nginx
        state: present
      when: ansible_distribution == "Amazon"
